export const VIEW_COURSE_REQUEST = "VIEW_COURSE_REQUEST";
export const VIEW_COURSE_SUCCESS = "VIEW_COURSE_SUCCESS";
export const VIEW_COURSE_FAIL = "VIEW_COURSE_FAIL";

export const SINGLE_COURSE_REQUEST = "SINGLE_COURSE_REQUEST";
export const SINGLE_COURSE_SUCCESS = "SINGLE_COURSE_SUCCESS";
export const SINGLE_COURSE_FAIL = "SINGLE_COURSE_FAIL";

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const CREATE_COURSE_RESET = "CREATE_COURSE_RESET";

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";
export const UPDATE_COURSE_RESET = "UPDATE_COURSE_RESET";

export const VIEW_COURSENAME_REQUEST = "VIEW_COURSENAME_REQUEST";
export const VIEW_COURSENAME_SUCCESS = "VIEW_COURSENAME_SUCCESS";
export const VIEW_COURSENAME_FAIL = "VIEW_COURSENAME_FAIL";
export const VIEW_COURSENAME_RESET = "VIEW_COURSENAME_RESET";
