export const REQUEST_REMINDER = "REQUEST_REMINDER";
export const ADD_REMINDER = "ADD_REMINDER";
export const REMOVE_REMINDER = "REMOVE_REMINDER";
export const VIEW_REMINDER = "VIEW_REMINDER";
export const RESET_REMINDER = "RESET_REMINDER";
