export const VIEW_RESOURCE_REQUEST = "VIEW_RESOURCE_REQUEST";
export const VIEW_RESOURCE_SUCCESS = "VIEW_RESOURCE_SUCCESS";
export const VIEW_RESOURCE_FAIL = "VIEW_RESOURCE_FAIL";

export const SINGLE_RESOURCE_REQUEST = "SINGLE_RESOURCE_REQUEST";
export const SINGLE_RESOURCE_SUCCESS = "SINGLE_RESOURCE_SUCCESS";
export const SINGLE_RESOURCE_FAIL = "SINGLE_RESOURCE_FAIL";

export const CREATE_RESOURCE_REQUEST = "CREATE_RESOURCE_REQUEST";
export const CREATE_RESOURCE_SUCCESS = "CREATE_RESOURCE_SUCCESS";
export const CREATE_RESOURCE_FAIL = "CREATE_RESOURCE_FAIL";
export const CREATE_RESOURCE_RESET = "CREATE_RESOURCE_RESET";

export const UPDATE_RESOURCE_REQUEST = "UPDATE_RESOURCE_REQUEST";
export const UPDATE_RESOURCE_SUCCESS = "UPDATE_RESOURCE_SUCCESS";
export const UPDATE_RESOURCE_FAIL = "UPDATE_RESOURCE_FAIL";
export const UPDATE_RESOURCE_RESET = "UPDATE_RESOURCE_RESET";

export const DELETE_RESOURCE_REQUEST = "DELETE_RESOURCE_REQUEST";
export const DELETE_RESOURCE_SUCCESS = "DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_FAIL = "DELETE_RESOURCE_FAIL";
export const DELETE_RESOURCE_RESET = "DELETE_RESOURCE_RESET";
