export const STAFF_LOGIN_REQUEST = "STAFF_LOGIN_REQUEST";
export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_FAIL = "STAFF_LOGIN_FAIL";

export const STAFF_REGISTER_REQUEST = "STAFF_REGISTER_REQUEST";
export const STAFF_REGISTER_SUCCESS = "STAFF_REGISTER_SUCCESS";
export const STAFF_REGISTER_FAIL = "STAFF_REGISTER_FAIL";

export const STAFF_DETAILS_REQUEST = "STAFF_DETAILS_REQUEST";
export const STAFF_DETAILS_SUCCESS = "STAFF_DETAILS_SUCCESS";
export const STAFF_DETAILS_FAIL = "STAFF_DETAILS_FAIL";
export const STAFF_DETAILS_RESET = "STAFF_DETAILS_RESET";

export const STAFF_UPDATE_PROFILE_REQUEST = "STAFF_UPDATE_PROFILE_REQUEST";
export const STAFF_UPDATE_PROFILE_SUCCESS = "STAFF_UPDATE_PROFILE_SUCCESS";
export const STAFF_UPDATE_PROFILE_FAIL = "STAFF_UPDATE_PROFILE_FAIL";
export const STAFF_UPDATE_PROFILE_RESET = "STAFF_UPDATE_PROFILE_RESET";

export const STAFF_FORGOT_PASSWORD_REQUEST = "STAFF_FORGOT_PASSWORD_REQUEST";
export const STAFF_FORGOT_PASSWORD_SUCCESS = "STAFF_FORGOT_PASSWORD_SUCCESS";
export const STAFF_FORGOT_PASSWORD_FAIL = "STAFF_FORGOT_PASSWORD_FAIL";

export const STAFF_RESET_PASSWORD_REQUEST = "STAFF_RESET_PASSWORD_REQUEST";
export const STAFF_RESET_PASSWORD_SUCCESS = "STAFF_RESET_PASSWORD_SUCCESS";
export const STAFF_RESET_PASSWORD_FAIL = "STAFF_RESET_PASSWORD_FAIL";

export const ADMIN_VIEW_STAFF_REQUEST = "ADMIN_VIEW_STAFF_REQUEST";
export const ADMIN_VIEW_STAFF_SUCCESS = "ADMIN_VIEW_STAFF_SUCCESS";
export const ADMIN_VIEW_STAFF_FAIL = "ADMIN_VIEW_STAFF_FAIL";

export const ADMIN_ASSIGN_REQUEST = "ADMIN_ASSIGN_REQUEST";
export const ADMIN_ASSIGN_SUCCESS = "ADMIN_ASSIGN_SUCCESS";
export const ADMIN_ASSIGN_FAIL = "ADMIN_ASSIGN_FAIL";
export const ADMIN_ASSIGN_RESET = "ADMIN_ASSIGN_RESET";
