export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const STUDENT_REGISTER_REQUEST = "STUDENT_REGISTER_REQUEST";
export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAIL = "STUDENT_REGISTER_FAIL";

export const STUDENT_DETAILS_REQUEST = "STUDENT_DETAILS_REQUEST";
export const STUDENT_DETAILS_SUCCESS = "STUDENT_DETAILS_SUCCESS";
export const STUDENT_DETAILS_FAIL = "STUDENT_DETAILS_FAIL";
export const STUDENT_DETAILS_RESET = "STUDENT_DETAILS_RESET";

export const STUDENT_UPDATE_PROFILE_REQUEST = "STUDENT_UPDATE_PROFILE_REQUEST";
export const STUDENT_UPDATE_PROFILE_SUCCESS = "STUDENT_UPDATE_PROFILE_SUCCESS";
export const STUDENT_UPDATE_PROFILE_FAIL = "STUDENT_UPDATE_PROFILE_FAIL";
export const STUDENT_UPDATE_PROFILE_RESET = "STUDENT_UPDATE_PROFILE_RESET";

export const STUDENT_FORGOT_PASSWORD_REQUEST =
  "STUDENT_FORGOT_PASSWORD_REQUEST";
export const STUDENT_FORGOT_PASSWORD_SUCCESS =
  "STUDENT_FORGOT_PASSWORD_SUCCESS";
export const STUDENT_FORGOT_PASSWORD_FAIL = "STUDENT_FORGOT_PASSWORD_FAIL";

export const STUDENT_RESET_PASSWORD_REQUEST = "STUDENT_RESET_PASSWORD_REQUEST";
export const STUDENT_RESET_PASSWORD_SUCCESS = "STUDENT_RESET_PASSWORD_SUCCESS";
export const STUDENT_RESET_PASSWORD_FAIL = "STUDENT_RESET_PASSWORD_FAIL";
